### ISSUE TITLE
Wrong Copyright 

### ISSUE THREAD

**Issue by riteshgaur** [Snooker57/Resume#1]
## Why your page has this? 

`Copyright&nbsp;©&nbsp;2017-2018&nbsp;&nbsp;www.baidu.com&nbsp;&nbsp;蜀ICP备13014270号-4`

Last time I check it's your code, not Baidu's!

**Suggestion:** _Don't use copyright and/or choose correct licence_

**Comment by Snooker57** [comment]
I just want to add a footer in my page, the correctness of licence is not considered,sorry,i will change it and push it again! @riteshgaur
